cars/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from cars.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home),
    path('app/',include('carsTestApp.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carsTestApp/urls.py
from django.urls import  path
from.views import   CreateOffer, DetBilan, DetOff, EspaceClient,  SignUP,LoginView,LogoutView,GetExpert,AddBilan,EspaceExpert,Update_Bilan,Update_Offre,OffreDelete
app_name="carsApp"

urlpatterns = [
     path('expert/espaceExpert',EspaceExpert,name='espace_expert'),
     path('expert/add',AddBilan,name='add_bilan'),
     path('expert/update/<int:pk>',Update_Bilan.as_view(),name='update_bilan'),
     
     
     
     
     path('client/listeExpert/<int:pk>',GetExpert,name='get_expert'),
     path('client/espaceClient', EspaceClient,name='espace_client'),
     path('client/espaceClientDet/<int:pk>',DetOff,name='offer_detail'),
     path('client/BilanDet/<int:pk>',DetBilan,name='bilan_detail'),
     
    
     path('client/createOffer', CreateOffer,name='createOffer'),
     path('client/signup', SignUP,name='signup'),
     path('client/update/<int:pk>',Update_Offre.as_view(),name='update_offer'),
     

     path('login',LoginView, name='login'),
     path('logout',LogoutView, name='logout'),
     path('client/espaceClient/<int:pk>',OffreDelete.as_view(),name='delete_offer'),

]

carsTestApp/models.py
from decimal import Decimal
from django.db import models
from tkinter import CASCADE

from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator, MaxValueValidator
PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]


# Create your models here.



# Create your models here.
class User(AbstractUser):
  is_client=models.BooleanField(default=False)
  is_expert=models.BooleanField(default=False)
class Expert(models.Model):
  user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,related_name='expert_user')
  first_name=None
  last_name=None
  notifie=models.BooleanField(default=False)
  # nbre_notification=models.IntegerField(default=0,null=True,blank=True)
  nom=models.CharField(max_length=50,unique=True)
  prenom=models.CharField(max_length=50)
  adresse_mail=models.EmailField(max_length=500)
  ARIANA='Ariana'
  TUNIS='Tunis'
  BENAROUS='Ben Arous'
  MANOUBA='Manouba'
  BEJA='Beja'
  BIZERTE='Bizerte'
  GABES='Gabes'
  GAFSA='Gafsa'
  JENDOUBA='Jendouba'
  KAIROUAN='Kairouan'
  KASSERINE='Kasserine'
  KEBILI='Kebili'
  KEF='Kef'
  MAHDIA='Mahdia'
  MEDENINE='Medenine'
  MONASTIR='Monastir'
  NABEUL='Nabeul'
  SFAX='Sfax'
  SIDIBOUZID='Sidi Bouzid'
  SILIANA='Siliana'
  SOUSSE='Sousse'
  TATAOUINE='Tataouine'
  TOUZEUR='Tozeur'
  ZAGHOUAN='Zaghouan'
  REGION=[(ARIANA,'Ariana'),(TUNIS,'Tunis'),(BENAROUS,'Ben Arous'),(MANOUBA,'Manouba'),(BEJA,'Beja'),(BIZERTE,'Bizerte'),(GABES,'Gabes'),(GAFSA,'Gafsa'),(JENDOUBA,'Jendouba'),(KAIROUAN,'Kairouan'),(KASSERINE,'Kasserine'),(KEBILI,'Kebili'),(KEF,'Kef'),(MAHDIA,'Mahdia'),(MEDENINE,'Medenine'),(MONASTIR,'Monastir'),(NABEUL,'Nabeul'),(SFAX,'Sfax'),(SIDIBOUZID,'Sidi Bouzid'),(SILIANA,'Siliana'),(SOUSSE,'Sousse'),(TATAOUINE,'Tataouine'),(TOUZEUR,'Tozeur'),(ZAGHOUAN,'Zaghouan')]
  region=models.CharField(max_length=20,choices=REGION,default=TUNIS)
  photo=models.ImageField(upload_to='cars/fichierExpert/photos')
  numero_de_téléphone = PhoneNumberField(blank=True)
  def __str__(self):
        return self.nom + self.prenom
  
class Client(models.Model):
  user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True) 
  name=models.CharField(max_length=40,default=None)
class Bilan_expert(models.Model):
  active=models.BooleanField(default=False)
  prix_suggéré=models.FloatField(default=0)
  note= models.DecimalField(max_digits=3, decimal_places=0, default=Decimal(0), validators=PERCENTAGE_VALIDATOR)
  batterie_cmd_electronique=models.CharField(max_length=200)
  tableau_de_bord_alertes_temoins_allumes=models.CharField(max_length=200)
  moteur_niveaux=models.CharField(max_length=200)
  fixation=models.CharField(max_length=200)
  courroies_accessoires=models.CharField(max_length=200)
  boite_vitesse_embrayage=models.CharField(max_length=200)
  echappement_pollution=models.CharField(max_length=200)
  identification=models.CharField(max_length=200)
  vision_eclairage_avertisseur_sonore=models.CharField(max_length=200)
  direction=models.CharField(max_length=200)
  train=models.CharField(max_length=200)
  transmission_roulement=models.CharField(max_length=200)
  jantes_pneus=models.CharField(max_length=200)
  freinage=models.CharField(max_length=200)
  suspension=models.CharField(max_length=200)
  infrastructure=models.CharField(max_length=200)
  aspect_carrosserie=models.CharField(max_length=200)
  interieur=models.CharField(max_length=200)
  clim_chauffage=models.CharField(max_length=200)
  essai_routier=models.CharField(max_length=200)
  commentaire=models.TextField()
  expert=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,related_name='exp')
  def __str__(self):
        return self.commentaire

class Offre(models.Model):
  matricule=models.CharField(max_length=30,unique=True)
  marque=models.CharField(max_length=30)
  couleur=models.CharField(max_length=30)
  region=models.CharField(max_length=40)
  puissance=models.CharField(max_length=10)
  cylindres=models.FloatField(default=0)
  kilometrage=models.FloatField(default=0)
  Automatique='auto'
  Manuelle='manuelle'
  TRANSMISSION=[(Automatique,'Auto'),(Manuelle,'manuelle')]
  transmission=models.CharField(max_length=20,choices=TRANSMISSION)
  carburant=models.CharField(max_length=30)
  annee=models.IntegerField(default=2000,verbose_name="année")
  image=models.ImageField(upload_to='cars/fichier/images',blank=True)
  prix_propose=models.FloatField(default=0)
  prix_enchere=models.FloatField(default=0,blank=True)
  vendeur=models.ForeignKey(User,on_delete=models.CASCADE,default=None,null=True,blank=True,related_name='vendeur_offre')
  expert=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,null=True,blank=True,related_name='exp_offre')
  bilan=models.OneToOneField(Bilan_expert,on_delete=models.CASCADE,null=True,blank=True,related_name='voiture_associée')
  def __str__(self):
        return self.matricule
class Commentaire(models.Model):
  contenu=models.TextField()
  cree_le = models.DateTimeField(auto_now_add=True)
  modifie_le = models.DateTimeField(auto_now=True)
  acheteur=models.ForeignKey(User,on_delete=models.CASCADE)
  offre=models.ForeignKey(Offre,related_name="comments",on_delete=models.CASCADE)
  def __str__(self):
        return self.contenu 
        
class Notification(models.Model):
  ident=models.IntegerField(default=100)
  exp_not=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,related_name='exp_notification')
  client_not=models.ForeignKey(User,on_delete=models.CASCADE,default=None,related_name='client_notification')
  number=models.IntegerField(default=0)
  def __str__(self):
    return f'{self.ident}  {self.exp_not} {self.client_not} {self.number}'

carsTestApp/views.py
from re import U
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect,HttpResponse

from django.core.paginator import Paginator
from .forms import   CommentsForm, OfferForm, RegisterForm, Bilan_expertForm,Bilan_expert_update_Form

from django.urls import reverse_lazy,reverse


from carsTestApp.models import Offre, Expert,User,Client,Bilan_expert
from django.core.paginator import Paginator

from django.views.generic import UpdateView,DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.mixins import PermissionRequiredMixin

#///////////////////////////////////////////////////////////////
    #CRUD using functions: 
    #get all elements: the first step consits on gettings all gthe cars, the second consists on serializing them and the third consists on returning json:
    #############################################################################################################################################################################
    #ESPACE EXPERT
    #############################################################################################################################################################################
@permission_required("carsTestApp.view_bilan_expert",raise_exception=True)
@login_required(login_url="/login/")
def EspaceExpert(request):
 liste_bilan=Bilan_expert.objects.all()
 if request.method=='POST':
     bilan_id=request.POST.get("bilan-id")
     bilan=Bilan_expert.objects.filter(id=bilan_id).first()
     bilan.delete()
 return render (request,'Expert/EspaceExpert.html',{"liste":liste_bilan})
#     #############################################################################################################################################################################
#     #ADD NEW BILAN
#     #############################################################################################################################################################################
@permission_required("carsTestApp.add_bilan_expert",raise_exception=True)
@login_required(login_url="/login/")
def AddBilan(request,**kwargs): 
  if request.method=='POST':
    bilan_expert_form=Bilan_expertForm(request.POST,user=request.user)
    x=request.POST.get("voiture")
    print(x)
    print(request.POST) 
    if bilan_expert_form.is_valid():
     bilan= bilan_expert_form.save(commit=False)
     bilan.expert_id = request.user.id
     bilan.active=True
     #getting the data from voiture_associée field
     data = bilan_expert_form.cleaned_data
     voiture_associée = data['voiture_associée']
     print(voiture_associée)
     get_matricule=Offre.objects.get(matricule=voiture_associée)
     print('la voiture est',get_matricule.matricule)
     bilan.save()
    #  bilan_expert_form.fields['voiture_associée'].queryset=Offre.objects.filter(~Offre(matricule=voiture_associée))
    
     get_all_offers=Offre.objects.all()
     print('les offres enregistrées',get_all_offers)
     for i in get_all_offers:
         if i.matricule==get_matricule.matricule:
           i.bilan_id=bilan.id
           i.prix_enchere=bilan.prix_suggéré
         i.save() 
     return redirect('/app/expert/espaceExpert')
    else:
      return HttpResponse('<h2> not valid </h2>')
  else:
    bilan_expert_form=Bilan_expertForm(user=request.user)
    dict={'form':bilan_expert_form}
    return render(request,'Expert/AddBilan.html',dict)
# #############################################################################################################################################################################
# #update bilan
# #############################################################################################################################################################################

class Update_Bilan(PermissionRequiredMixin,UpdateView):
   permission_required='carsTestApp.schange_bilan_expert'
   model = Bilan_expert
  #  fields='__all__'
   form_class=Bilan_expert_update_Form
   template_name = "Expert/UpdateBilan.html"
   success_url=reverse_lazy('carsApp:espace_expert')

# #############################################################################################################################################################################
def DetBilan(request,  **kwargs):
  pk = int(kwargs['pk'])
  bilanbyid=Bilan_expert.objects.get(pk=pk)
  bilanbyiddic={"bilanid":bilanbyid,'pk':pk}
  return render(request,'Expert/Bilan.html',bilanbyiddic)
#############################################################################################################################################################################
#ESPACE CLIENT
#############################################################################################################################################################################

def EspaceClient(request,**kwargs):
 if request.method=='POST':
  pk = int(kwargs['pk'])
  offerid=Offre.objects.get(pk=pk)
  print(offerid)

 else: 
    offres=Offre.objects.all()
    p=Paginator(offres,3)
    pagenum=request.GET.get('page',1)
    numEle=p.count #nombre total d'élements 
    print("le nombre total d'elements est:" ,numEle)
    nbPages=p.num_pages
    print("le nombre de pages est:",nbPages) #nombre de  pages
    for i in range (1,nbPages+1):
       elementperpage=p.page(i).object_list
       print("les elements de la page", i ,"sont: ", elementperpage,"\n")     
    try:
          page=p.page(pagenum) 
    except EmptyPage:
       page=p.page(1) 
    offresDict={"ListeOffres":offres,"item":page}
    return render(request,'Client/EspaceClient.html',offresDict)
#############################################################################################################################################################################
#détails d'une offre
#############################################################################################################################################################################
def DetOff(request,  **kwargs):
  pk = int(kwargs['pk'])
  offerbyid=Offre.objects.get(pk=pk)
  if request.method=='POST':
    form=CommentsForm(request.POST)
    if form.is_valid():
      comment=form.save(commit=False)
      comment.acheteur = request.user
      comment.offre_id=kwargs['pk']
      comment.save()
      return HttpResponseRedirect(reverse("carsApp:offer_detail", kwargs={'pk':pk}))
  else:     
   form=CommentsForm()
   offerbyiddic={"offreid":offerbyid,"form":form}
   return render(request,'Client/OfferDetail.html',offerbyiddic)

#############################################################################################################################################################################
#SIGN-UP
#############################################################################################################################################################################
def SignUP (request):
  if request.method=='POST':
    form=RegisterForm(request.POST)
    if form.is_valid():
      user=form.save(commit=False)
      user.is_client=True
    #   user.first_name=form.cleaned_data.get('first_name')
    #   user.last_name=form.cleaned_data.get('last_name')
      user=form.save()
      print("the user is",user)
      print("the user is a client=",user.is_client)
      client=Client.objects.create(user_id=user.id,name=user.username)
      print("from user to client is",client)
      client=form.save(commit=False)
    #   client.name=user.username
      client=form.save()
      print("le client est",client)
      login(request,user)
      messages.success(request,f"account was created for  {user.username}")
      return redirect('/app/client/espaceClient')
  else:
    form=RegisterForm()    
    
  return render(request,'Client/SignUp.html',{'form':form})



#########################################################################################################################
#create offer
#########################################################################################################################
@login_required(login_url="app/login")
def CreateOffer(request):
 if User.is_client:
  if request.method=='POST':
    offerform=OfferForm(request.POST,request.FILES)
    if offerform.is_valid():
      offer=offerform.save(commit=False)
      offer.vendeur=request.user
      offer.save()
      return redirect('/app/client/espaceClient')
  else:
    offerform=OfferForm()
  return render (request,'Client/CreateOffer.html',{'form':offerform})
#########################################################################################################################
#login 
#########################################################################################################################
def LoginView(request):
  if request.method=="POST":
    username=request.POST['username']
    password=request.POST['password']
    user=authenticate(request,username=username,password=password)
    if user is not None and user.is_client:
      print("theuseris",user.username,user.password)
      login(request,user)
      return redirect('carsApp:espace_client')
    elif user is not None and user.is_expert:
      login(request,user)
      return redirect('carsApp:espace_expert')
    else:
      return redirect('carsApp:login')
  else:
    return render(request,'registration/login.html')


#########################################################################################################################
#logout
#########################################################################################################################
def LogoutView(request):
   logout(request)
   messages.info(request, "Logged out successfully!")
   return redirect('carsApp:login')

carsTestApp/templates/Expert/AddBilan.html
{%extends 'Expert/NavbarExpert.html' %}
{%block content%}
{%load widget_tweaks%}
<!DOCTYPE html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <h2>BILAN EXPERT</h2>
   <div class="container">
    <form  action="" method="post">
    {% csrf_token%}
   {{form.as_p}}
    
   </div>
   <button type="submit" class="btn btn-primary" value="envoyer">soumettre</button>
   </form>
</body>
{%endblock%}

carsTestApp/templates/Expert/EspaceExpert.html
{%extends 'Expert/NavbarExpert.html'%}
{%block content%}
{% load static %}
<!DOCTYPE html>
<head>
  
    <link rel="stylesheet" type="text/css" href=" {% static '/cars/home.css' %} ">


<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>

<h2>BIENVENUE DANS L'ESPACE EXPERT</h2>
{%for i in liste%}
<!--
<p>{{i.expert}}</p>
<p>{{i.commentaire}}</p>-->


<div class="container mt-5 d-flex justify-content-left">

  <div class="card p-3">
    
      <div class="d-flex align-items-center">
        
          <div class="image">
          <img  src="{{i.voiture_associée.image.url}}" class="rounded" width="220"  alt="no image">
          </div>
        
   
      <div class="ml-3 w-100">
          
         <h4 class="mb-0 mt-0">  {{i.expert.nom}}   {{i.expert.prenom}} </h4>
        
            <span> matricule :  {{i.voiture_associée.matricule}}</span>
        
         <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">

          <div class="d-flex flex-column">

              <span class="articles">remarques  expert</span>
              <span class="number1">{{i.commentaire}}</span>
              
          </div>
        </div>
          <!--<div class="d-flex flex-column">

              <span class="followers">Followers</span>
              <span class="number2">980</span>
              
          </div>-->

          <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">
          <div class="d-flex flex-column">

              <span class="rating">score bilan</span>
              <span class="number3">{{i.note}}%</span>
              
          </div>
             
         </div>

         {%if user.id == i.expert_id %}
         <form action="" method="post">
           {% csrf_token %}
         <div class="button mt-2 d-flex flex-row align-items-center">
          
          <a class="btn btn-sm btn-outline-primary w-100" href="{% url 'carsApp:update_bilan'  i.id%}" role="button">Modifier</a>
          <button class="btn btn-sm btn-danger w-100 ml-2"   value={{i.id}} name="bilan-id" type="submit">Supprimer</button>

         
         </div>
        </form>
         {% endif %}
      </div>

          
      </div>
      
  </div>
   
</div>
<!--
  {%if user == i.expert %}
  <form action="" method="post">
    {% csrf_token %}
  <a class="btn btn-success" href="{% url 'carsApp:update_bilan'  i.id%}" role="button">Modifier</a> 
  <button  value={{i.id}} name="bilan-id" class="btn btn-danger" type="submit" >Supprimer</button> 
  </form>
  {% endif %}
-->
{%endfor%}

</body>
{%endblock%}

carsTestApp/templates/Expert/NavbarExpert.html
{% load static %}    
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css"  href="{% static '/carsAppTest/ExpertHome.css' %}"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>






<body>
    {%if user.is_authenticated%}
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
       
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'carsApp:espace_expert'%}">All reports</a>
              </li>
              <li>
                <a href="" class="font-weight-bolder text-success nav-link"><i class="fa fa-bell"><span class='badge badge-pill'>{{user.expert_user.exp_offre.count}}</span></i> Notifications</a>
                <!--<a href="" class="font-weight-bolder text-success nav-link"><i class="fa fa-bell"><span class='badge badge-pill'>{{user.expert_user.exp.active.count}}</span></i> Notification</a>-->
               </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'carsApp:add_bilan' %}">Add report</a>
                </li>   
            </ul> 
            <ul  class="navbar-nav margin-rigth:auto mb-2 mb-lg-0" >
                <li class="nav-item"> 
                <a class="nav-link" href="{%url 'carsApp:logout' %}">LOGOUT</a>
            </li>
              </ul>
              
            <span class="navbar-text">
              <svg style="margin-top: -5px;margin-right:5px" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
              </svg>{{user.expert_user.nom}} {{user.expert_user.prenom}}
            </span>
          </div>
        </div>
      </nav>
      {%else%}
      <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <div class="container-fluid">
       
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'carsApp:espace_expert'%}">tous les bilans</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{%url 'carsApp:add_bilan' %}">Ajouter un  bilan</a>   
                </li>
                <li class="nav-item">
                  <a class="nav-link"href="{%url 'carsApp:login' %}">LOGIN</a>   
                  </li>
            </ul> 
            
          </div>
        </div>
      </nav>
      {%endif%}
   <div class="container">
    {% block content%}{% endblock %}
   </div>
</body>

carsTestApp/templates/Expert/UpdateBilan.html
{%extends 'Expert/NavbarExpert.html'%}
{%block content%}

<!DOCTYPE html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>


<h3>UPDATE BILAN</h3>

<form method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-success">valider</button>

</form>
 </body>
 {%endblock%}