cars/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from cars.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home),
    path('app/',include('carsTestApp.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carsTestApp/urls.py
from django.urls import  path
from.views import   CreateOffer, DetBilan, DetOff, EspaceClient,  SignUP,LoginView,LogoutView,GetExpert,AddBilan,EspaceExpert,Update_Bilan,Update_Offre,OffreDelete
app_name="carsApp"

urlpatterns = [
     path('expert/espaceExpert',EspaceExpert,name='espace_expert'),
     path('expert/add',AddBilan,name='add_bilan'),
     path('expert/update/<int:pk>',Update_Bilan.as_view(),name='update_bilan'),
     
     
     
     
     path('client/listeExpert/<int:pk>',GetExpert,name='get_expert'),
     path('client/espaceClient', EspaceClient,name='espace_client'),
     path('client/espaceClientDet/<int:pk>',DetOff,name='offer_detail'),
     path('client/BilanDet/<int:pk>',DetBilan,name='bilan_detail'),
     
    
     path('client/createOffer', CreateOffer,name='createOffer'),
     path('client/signup', SignUP,name='signup'),
     path('client/update/<int:pk>',Update_Offre.as_view(),name='update_offer'),
     

     path('login',LoginView, name='login'),
     path('logout',LogoutView, name='logout'),
     path('client/espaceClient/<int:pk>',OffreDelete.as_view(),name='delete_offer'),

]

carsTestApp/models.py
from decimal import Decimal
from django.db import models
from tkinter import CASCADE

from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator, MaxValueValidator
PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]


# Create your models here.



# Create your models here.
class User(AbstractUser):
  is_client=models.BooleanField(default=False)
  is_expert=models.BooleanField(default=False)
class Expert(models.Model):
  user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,related_name='expert_user')
  first_name=None
  last_name=None
  notifie=models.BooleanField(default=False)
  # nbre_notification=models.IntegerField(default=0,null=True,blank=True)
  nom=models.CharField(max_length=50,unique=True)
  prenom=models.CharField(max_length=50)
  adresse_mail=models.EmailField(max_length=500)
  ARIANA='Ariana'
  TUNIS='Tunis'
  BENAROUS='Ben Arous'
  MANOUBA='Manouba'
  BEJA='Beja'
  BIZERTE='Bizerte'
  GABES='Gabes'
  GAFSA='Gafsa'
  JENDOUBA='Jendouba'
  KAIROUAN='Kairouan'
  KASSERINE='Kasserine'
  KEBILI='Kebili'
  KEF='Kef'
  MAHDIA='Mahdia'
  MEDENINE='Medenine'
  MONASTIR='Monastir'
  NABEUL='Nabeul'
  SFAX='Sfax'
  SIDIBOUZID='Sidi Bouzid'
  SILIANA='Siliana'
  SOUSSE='Sousse'
  TATAOUINE='Tataouine'
  TOUZEUR='Tozeur'
  ZAGHOUAN='Zaghouan'
  REGION=[(ARIANA,'Ariana'),(TUNIS,'Tunis'),(BENAROUS,'Ben Arous'),(MANOUBA,'Manouba'),(BEJA,'Beja'),(BIZERTE,'Bizerte'),(GABES,'Gabes'),(GAFSA,'Gafsa'),(JENDOUBA,'Jendouba'),(KAIROUAN,'Kairouan'),(KASSERINE,'Kasserine'),(KEBILI,'Kebili'),(KEF,'Kef'),(MAHDIA,'Mahdia'),(MEDENINE,'Medenine'),(MONASTIR,'Monastir'),(NABEUL,'Nabeul'),(SFAX,'Sfax'),(SIDIBOUZID,'Sidi Bouzid'),(SILIANA,'Siliana'),(SOUSSE,'Sousse'),(TATAOUINE,'Tataouine'),(TOUZEUR,'Tozeur'),(ZAGHOUAN,'Zaghouan')]
  region=models.CharField(max_length=20,choices=REGION,default=TUNIS)
  photo=models.ImageField(upload_to='cars/fichierExpert/photos')
  numero_de_téléphone = PhoneNumberField(blank=True)
  def __str__(self):
        return self.nom + self.prenom
  
class Client(models.Model):
  user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True) 
  name=models.CharField(max_length=40,default=None)
class Bilan_expert(models.Model):
  active=models.BooleanField(default=False)
  prix_suggéré=models.FloatField(default=0)
  note= models.DecimalField(max_digits=3, decimal_places=0, default=Decimal(0), validators=PERCENTAGE_VALIDATOR)
  batterie_cmd_electronique=models.CharField(max_length=200)
  tableau_de_bord_alertes_temoins_allumes=models.CharField(max_length=200)
  moteur_niveaux=models.CharField(max_length=200)
  fixation=models.CharField(max_length=200)
  courroies_accessoires=models.CharField(max_length=200)
  boite_vitesse_embrayage=models.CharField(max_length=200)
  echappement_pollution=models.CharField(max_length=200)
  identification=models.CharField(max_length=200)
  vision_eclairage_avertisseur_sonore=models.CharField(max_length=200)
  direction=models.CharField(max_length=200)
  train=models.CharField(max_length=200)
  transmission_roulement=models.CharField(max_length=200)
  jantes_pneus=models.CharField(max_length=200)
  freinage=models.CharField(max_length=200)
  suspension=models.CharField(max_length=200)
  infrastructure=models.CharField(max_length=200)
  aspect_carrosserie=models.CharField(max_length=200)
  interieur=models.CharField(max_length=200)
  clim_chauffage=models.CharField(max_length=200)
  essai_routier=models.CharField(max_length=200)
  commentaire=models.TextField()
  expert=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,related_name='exp')
  def __str__(self):
        return self.commentaire

class Offre(models.Model):
  matricule=models.CharField(max_length=30,unique=True)
  marque=models.CharField(max_length=30)
  couleur=models.CharField(max_length=30)
  region=models.CharField(max_length=40)
  puissance=models.CharField(max_length=10)
  cylindres=models.FloatField(default=0)
  kilometrage=models.FloatField(default=0)
  Automatique='auto'
  Manuelle='manuelle'
  TRANSMISSION=[(Automatique,'Auto'),(Manuelle,'manuelle')]
  transmission=models.CharField(max_length=20,choices=TRANSMISSION)
  carburant=models.CharField(max_length=30)
  annee=models.IntegerField(default=2000,verbose_name="année")
  image=models.ImageField(upload_to='cars/fichier/images',blank=True)
  prix_propose=models.FloatField(default=0)
  prix_enchere=models.FloatField(default=0,blank=True)
  vendeur=models.ForeignKey(User,on_delete=models.CASCADE,default=None,null=True,blank=True,related_name='vendeur_offre')
  expert=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,null=True,blank=True,related_name='exp_offre')
  bilan=models.OneToOneField(Bilan_expert,on_delete=models.CASCADE,null=True,blank=True,related_name='voiture_associée')
  def __str__(self):
        return self.matricule
class Commentaire(models.Model):
  contenu=models.TextField()
  cree_le = models.DateTimeField(auto_now_add=True)
  modifie_le = models.DateTimeField(auto_now=True)
  acheteur=models.ForeignKey(User,on_delete=models.CASCADE)
  offre=models.ForeignKey(Offre,related_name="comments",on_delete=models.CASCADE)
  def __str__(self):
        return self.contenu 
        
class Notification(models.Model):
  ident=models.IntegerField(default=100)
  exp_not=models.ForeignKey(Expert,on_delete=models.CASCADE,default=None,related_name='exp_notification')
  client_not=models.ForeignKey(User,on_delete=models.CASCADE,default=None,related_name='client_notification')
  number=models.IntegerField(default=0)
  def __str__(self):
    return f'{self.ident}  {self.exp_not} {self.client_not} {self.number}'

carsTestApp/views.py
from re import U
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect,HttpResponse

from django.core.paginator import Paginator
from .forms import   CommentsForm, OfferForm, RegisterForm, Bilan_expertForm,Bilan_expert_update_Form

from django.urls import reverse_lazy,reverse


from carsTestApp.models import Offre, Expert,User,Client,Bilan_expert
from django.core.paginator import Paginator

from django.views.generic import UpdateView,DeleteView
from django.contrib import messages
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.mixins import PermissionRequiredMixin

#///////////////////////////////////////////////////////////////
    #CRUD using functions: 
    #get all elements: the first step consits on gettings all gthe cars, the second consists on serializing them and the third consists on returning json:
    #############################################################################################################################################################################
    #ESPACE EXPERT
    #############################################################################################################################################################################
@permission_required("carsTestApp.view_bilan_expert",raise_exception=True)
@login_required(login_url="/login/")
def EspaceExpert(request):
 liste_bilan=Bilan_expert.objects.all()
 if request.method=='POST':
     bilan_id=request.POST.get("bilan-id")
     bilan=Bilan_expert.objects.filter(id=bilan_id).first()
     bilan.delete()
 return render (request,'Expert/EspaceExpert.html',{"liste":liste_bilan})
#     #############################################################################################################################################################################
#     #ADD NEW BILAN
#     #############################################################################################################################################################################
@permission_required("carsTestApp.add_bilan_expert",raise_exception=True)
@login_required(login_url="/login/")
def AddBilan(request,**kwargs): 
  if request.method=='POST':
    bilan_expert_form=Bilan_expertForm(request.POST,user=request.user)
    x=request.POST.get("voiture")
    print(x)
    print(request.POST) 
    if bilan_expert_form.is_valid():
     bilan= bilan_expert_form.save(commit=False)
     bilan.expert_id = request.user.id
     bilan.active=True
     #getting the data from voiture_associée field
     data = bilan_expert_form.cleaned_data
     voiture_associée = data['voiture_associée']
     print(voiture_associée)
     get_matricule=Offre.objects.get(matricule=voiture_associée)
     print('la voiture est',get_matricule.matricule)
     bilan.save()
    #  bilan_expert_form.fields['voiture_associée'].queryset=Offre.objects.filter(~Offre(matricule=voiture_associée))
    
     get_all_offers=Offre.objects.all()
     print('les offres enregistrées',get_all_offers)
     for i in get_all_offers:
         if i.matricule==get_matricule.matricule:
           i.bilan_id=bilan.id
           i.prix_enchere=bilan.prix_suggéré
         i.save() 
     return redirect('/app/expert/espaceExpert')
    else:
      return HttpResponse('<h2> not valid </h2>')
  else:
    bilan_expert_form=Bilan_expertForm(user=request.user)
    dict={'form':bilan_expert_form}
    return render(request,'Expert/AddBilan.html',dict)
# #############################################################################################################################################################################
# #update bilan
# #############################################################################################################################################################################

class Update_Bilan(PermissionRequiredMixin,UpdateView):
   permission_required='carsTestApp.schange_bilan_expert'
   model = Bilan_expert
  #  fields='__all__'
   form_class=Bilan_expert_update_Form
   template_name = "Expert/UpdateBilan.html"
   success_url=reverse_lazy('carsApp:espace_expert')

# #############################################################################################################################################################################
def DetBilan(request,  **kwargs):
  pk = int(kwargs['pk'])
  bilanbyid=Bilan_expert.objects.get(pk=pk)
  bilanbyiddic={"bilanid":bilanbyid,'pk':pk}
  return render(request,'Expert/Bilan.html',bilanbyiddic)
#############################################################################################################################################################################
#ESPACE CLIENT
#############################################################################################################################################################################

def EspaceClient(request,**kwargs):
 if request.method=='POST':
  pk = int(kwargs['pk'])
  offerid=Offre.objects.get(pk=pk)
  print(offerid)

 else: 
    offres=Offre.objects.all()
    p=Paginator(offres,3)
    pagenum=request.GET.get('page',1)
    numEle=p.count #nombre total d'élements 
    print("le nombre total d'elements est:" ,numEle)
    nbPages=p.num_pages
    print("le nombre de pages est:",nbPages) #nombre de  pages
    for i in range (1,nbPages+1):
       elementperpage=p.page(i).object_list
       print("les elements de la page", i ,"sont: ", elementperpage,"\n")     
    try:
          page=p.page(pagenum) 
    except EmptyPage:
       page=p.page(1) 
    offresDict={"ListeOffres":offres,"item":page}
    return render(request,'Client/EspaceClient.html',offresDict)
#############################################################################################################################################################################
#détails d'une offre
#############################################################################################################################################################################
def DetOff(request,  **kwargs):
  pk = int(kwargs['pk'])
  offerbyid=Offre.objects.get(pk=pk)
  if request.method=='POST':
    form=CommentsForm(request.POST)
    if form.is_valid():
      comment=form.save(commit=False)
      comment.acheteur = request.user
      comment.offre_id=kwargs['pk']
      comment.save()
      return HttpResponseRedirect(reverse("carsApp:offer_detail", kwargs={'pk':pk}))
  else:     
   form=CommentsForm()
   offerbyiddic={"offreid":offerbyid,"form":form}
   return render(request,'Client/OfferDetail.html',offerbyiddic)

#############################################################################################################################################################################
#SIGN-UP
#############################################################################################################################################################################
def SignUP (request):
  if request.method=='POST':
    form=RegisterForm(request.POST)
    if form.is_valid():
      user=form.save(commit=False)
      user.is_client=True
    #   user.first_name=form.cleaned_data.get('first_name')
    #   user.last_name=form.cleaned_data.get('last_name')
      user=form.save()
      print("the user is",user)
      print("the user is a client=",user.is_client)
      client=Client.objects.create(user_id=user.id,name=user.username)
      print("from user to client is",client)
      client=form.save(commit=False)
    #   client.name=user.username
      client=form.save()
      print("le client est",client)
      login(request,user)
      messages.success(request,f"account was created for  {user.username}")
      return redirect('/app/client/espaceClient')
  else:
    form=RegisterForm()    
    
  return render(request,'Client/SignUp.html',{'form':form})



#########################################################################################################################
#create offer
#########################################################################################################################
@login_required(login_url="app/login")
def CreateOffer(request):
 if User.is_client:
  if request.method=='POST':
    offerform=OfferForm(request.POST,request.FILES)
    if offerform.is_valid():
      offer=offerform.save(commit=False)
      offer.vendeur=request.user
      offer.save()
      return redirect('/app/client/espaceClient')
  else:
    offerform=OfferForm()
  return render (request,'Client/CreateOffer.html',{'form':offerform})
#########################################################################################################################
#login 
#########################################################################################################################
def LoginView(request):
  if request.method=="POST":
    username=request.POST['username']
    password=request.POST['password']
    user=authenticate(request,username=username,password=password)
    if user is not None and user.is_client:
      print("theuseris",user.username,user.password)
      login(request,user)
      return redirect('carsApp:espace_client')
    elif user is not None and user.is_expert:
      login(request,user)
      return redirect('carsApp:espace_expert')
    else:
      return redirect('carsApp:login')
  else:
    return render(request,'registration/login.html')


#########################################################################################################################
#logout
#########################################################################################################################
def LogoutView(request):
   logout(request)
   messages.info(request, "Logged out successfully!")
   return redirect('carsApp:login')

carsTestApp/templates/Client/CreateOffer.html
{% extends 'Client/navbar.html'%}

{% load crispy_forms_tags %} 
{% load static %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{% static 'carsTestApp/OfferDetail.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
{% block content%}
<h3>Add a new car</h3>

<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{form|crispy}}
    <button type="submit" class="btn btn-primary">post</button>
    
    
</form>

{% endblock %}

carsTestApp/templates/Client/EspaceClient.html
{% extends 'Client/navbar.html'%} {% load crispy_forms_tags %} 
{%load static%}

<!DOCTYPE html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'carsAppTest/OfferDetail.css' %}"/>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
{% block content%}
<br>
<h1 style="background-color: white; margin-left: 580px; margin-right: 580px ;text-align: center ; font-family: 'fantasy'; color:rgb(44, 43, 43); font-weight: 900"></h1>
<hr>
<div class="container">

<div class="row">
    {%for i in ListeOffres%}
        <div class="col d-flex align-items-stretch" style=" margin-bottom: 40px">
            <div class="card" style="  margin-right: auto;
            margin-left: auto;
            
            box-shadow: 0 15px 25px rgba(129, 124, 124, 0.2);
            
            border-radius: 5px;
            backdrop-filter: blur(14px);
            background-color: rgba(255, 255, 255, 0.2);
            padding: 35px;
            text-align: center; ">
            <h3 style="text-align: left">{{i.marque}} </h3> 
            <h6 style="text-align: right ;font-family: 'georgia'">Posted by: {{i.vendeur}} <h6>
            {% if i.image %}
            <a  href="{% url 'carsApp:offer_detail'  i.id %}"> <img style="border: 2px solid rgba(156, 156, 156, 0.396); padding: 4px" src="{{i.image.url}}"  width=330 height=220>  </img></a>
            {% endif %}


            <h4 style="text-align: left ;font-weight: 400; color: white">Color:  {{i.couleur}}</h4>
            <h4 style="text-align: left; font-weight: 400; color: white">Client's price:  {{i.prix_propose}}</h4>
            <h4 style="text-align: left;font-weight: 400; color: white">Expert's price:  {{i.prix_enchere}}</h4>
            {% if i.expert_id is NULL  %}
            <a type="button" class="btn btn-primary"  href="{% url 'carsApp:get_expert' i.id %}"> gérer expert </a><br>
            {%endif%}
            <!--{% if i.expert_id.notife is  TRUE %}
            <a type="button" class="btn btn-danger"  href="{% url 'carsApp:get_expert' i.id %}">alert </a>
            {%endif%}-->
            {%if user == i.vendeur%}
            <a class="btn btn-sm btn-outline-dark w-100" style=" margin-top: 12px" href="{% url 'carsApp:update_offer'  i.id%}"  role="button">Edit</a>
            <a class="btn btn-sm btn-outline-danger w-100" style=" margin-top: 12px" href="{% url 'carsApp:delete_offer' i.id %}" role="button">delete</a>
            {%endif%}
          

           

        </div> 
    <br>
    </div> 
    

{%empty%}
<div class="alert alert-danger" role="alert" >
     NO OFFERS YET :( 
</div>

{% endfor %}
</div> 

</div><br>

{%endblock%}

carsTestApp/templates/Client/OfferDetail.html
{%extends 'Client/Navbar.html'%}
{%load widget_tweaks%}
{%block content%}
{% load static %}
<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href=" {% static '/carsAppTest/OfferDetail.css' %} ">

</head>

<body>
  
{% load crispy_forms_tags %} 

<!--<img src="{% static 'carsAppTest/Ccoala1.jpg'%}"  alt="my image"/>-->
<!--<h3>ici on trouve tous les détails d'une offre à savoir tous les commentaire </h3>

<p>{{offreid.matricule}}</p>
<h3>comments...</h3>
{% if not offreid.comments.all %}
NO COMMENTS YET ...<a href="#">add one </a>
{%else%}
  {%for comment in offreid.comments.all%}
 <strong> {{comment.contenu}}-</strong>
  {{comment.acheteur}}-
  {{comment.cree_le}}
 
  {%endfor%}
{%endif%}
{% if user.is_authenticated %}
   <form method="POST">
     {% csrf_token %} {{form|crispy}}
   
     <button type="submit" class="btn btn-primary"> post</button>
{% endif %}
  </form>-->
 
<!-- Main Body -->
<p style="font-size: 50px; font-weight: ; margin-left: 10px">{{offreid.marque}}</p>
<div style=" margin-right: auto;
margin-left: auto;

box-shadow: 0 15px 25px rgba(129, 124, 124, 0.2);

border-radius: 5px;
backdrop-filter: blur(14px);
background-color: rgba(255, 255, 255, 0.2);
padding: 35px;
text-align: left ;">
<div class="container" style="">
    <img style="border: 2px solid rgba(156, 156, 156, 0.396); padding: 4px" src="{{offreid.image.url}}" alt="" />
    <p class="title">check Report</p>
    <div class="overlay"></div>
    {%if offreid.bilan_id is not NULL%}
    
    <div class="button"><a href="{% url 'carsApp:bilan_detail' offreid.bilan.id %}"> Expert Report </a></div>
    {%else%}
     
    <div class="button" style="font-size: 200%; color: white">  Expert report not found! </div>
    {%endif%}
</div>
<hr style="margin: 30px;">
<div  class="alert" >
<p style="font-size: 30px; Color: white ; margin-left: 10px">Plate number:  {{offreid.matricule}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Color:{{offreid.couleur}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px"> Region: {{offreid.region}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Mileage:  {{offreid.kilometrage}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Transmission: {{offreid.transmission}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Fuel type:   {{offreid.carburant}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Year:  {{offreid.annee}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Seller's price: {{offreid.prix_propose}}</p>
<p style="font-size: 30px; Color: white ; margin-left: 10px">Expert's price: {{offreid.prix_enchere}}</p>
</div>
<hr style="margin: 30px;">
</div>
<!--
<div>
    <p style="font-size: 50px; font-weight: ; margin-left: 10px">{{offreid.matricule}}</p>
    <img style="border: 2px solid rgba(156, 156, 156, 0.396); text-align: center ; padding: 4px" src="{{offreid.image.url}}" width=720 height=420>  </img>
    {%if offreid.bilan_id is not NULL%}
    <a type='button' class='btn btn-primary btn-sm' style="width: 100px; height: 50px" href="{% url 'carsApp:bilan_detail' offreid.bilan.id %}">bilan</a>
    {%else%}
    <div class="alert alert-warning" role="alert">
        pas de bilan pour cette offre
    </div>
  
    {%endif%}
</div> -->


{% if not offreid.comments.all %}
  <p style="color: white;">NO COMMENTS YET ... </p>
{%else%}  
<div>
   <section >

    <div class="container">
        <h1>Comments</h1>
        {%for comment in offreid.comments.all%}
        <div class="row">
            <div class="col">
                <div class="comment mt-4 me-auto">
                    <h4  style="text-align:left">{{comment.acheteur}}</h4>
                    <span style="text-align:left">- {{comment.cree_le}}</span>
                    <br>
                    <p style="text-align:left">{{comment.contenu}}</p>
                </div>
        
            </div>
         {%endfor%}
        </section>
{%endif%}
        
{% if user.is_authenticated %}
            
 <div class="form-row">
                
    <form method="POST"   id="algin-form">
        {% csrf_token %}
        
        <div class="form-group">
                     
            <h4>Leave a comment..</h4>
            
             {% render_field form.contenu rows="5 cols="30" name="msg  id=""msg class="form-control" %}        
           
              </div>
                    <div class="form-group" style="text-align: right">
                        <button type="submit" id="post"  class="btn" >Post Comment</button>
                    
                    </div>
                </form>
            </div>
{%endif%}
        </div>
    </div>

</div>
{%endblock%}
<br>
<br>
  </body>
  

carsTestApp/templates/Client/UpdateOffer.html
{%extends 'Client/navbar.html'%}
{%block content%}

<!DOCTYPE html>
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
<form method="POST" style="  margin-right: auto;
margin-left: auto;

box-shadow: 0 15px 25px rgba(129, 124, 124, 0.2);

border-radius: 5px;
backdrop-filter: blur(14px);
background-color: rgba(255, 255, 255, 0.2);
padding: 35px;
text-align: center; ">
<h3 style="margin-left: 30px">UPDATE</h3>
    {%csrf_token%}
    {{form.as_p}}
    <button class="btn btn-success">Save</button>

</form>
 </body>
 {%endblock%}